from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

main = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'USB_C_16P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_C_16P'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_USB:USB_C_Receptacle_GCT_USB4105-xx-A_16P_TopMnt_Horizontal', 'keywords':None, 'description':'USB-C 16P receptacle, GCT USB4105 class', 'datasheet':None, 'pins':[
            Pin(num='A1',name='GND_A1',func=pin_types.PWRIN),
            Pin(num='A4',name='VBUS_A4',func=pin_types.PWRIN),
            Pin(num='A5',name='CC1',func=pin_types.BIDIR),
            Pin(num='A6',name='DP1',func=pin_types.BIDIR),
            Pin(num='A7',name='DN1',func=pin_types.BIDIR),
            Pin(num='A8',name='SBU1',func=pin_types.PASSIVE),
            Pin(num='A9',name='VBUS_A9',func=pin_types.PWRIN),
            Pin(num='A12',name='GND_A12',func=pin_types.PWRIN),
            Pin(num='B1',name='GND_B1',func=pin_types.PWRIN),
            Pin(num='B4',name='VBUS_B4',func=pin_types.PWRIN),
            Pin(num='B5',name='CC2',func=pin_types.BIDIR),
            Pin(num='B6',name='DP2',func=pin_types.BIDIR),
            Pin(num='B7',name='DN2',func=pin_types.BIDIR),
            Pin(num='B8',name='SBU2',func=pin_types.PASSIVE),
            Pin(num='B9',name='VBUS_B9',func=pin_types.PWRIN),
            Pin(num='B12',name='GND_B12',func=pin_types.PWRIN),
            Pin(num='S1',name='SHIELD',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'TESTPOINT', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TESTPOINT'}), 'ref_prefix':'TP', 'fplist':None, 'footprint':'TestPoint:TestPoint_Pad_1.0x1.0mm', 'keywords':None, 'description':'Test pad', 'datasheet':None, 'pins':[
            Pin(num='1',name='TP',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'CYPD3177', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CYPD3177'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:HVQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm', 'keywords':None, 'description':'CYPD3177 autonomous USB-C PD sink; straps set 5V/3A request', 'datasheet':None, 'pins':[
            Pin(num='1',name='VBUS',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='CC1',func=pin_types.BIDIR),
            Pin(num='4',name='CC2',func=pin_types.BIDIR),
            Pin(num='5',name='VBUS_MIN',func=pin_types.INPUT),
            Pin(num='6',name='VBUS_MAX',func=pin_types.INPUT),
            Pin(num='7',name='ISNK_COARSE',func=pin_types.INPUT),
            Pin(num='8',name='ISNK_FINE',func=pin_types.INPUT),
            Pin(num='9',name='FAULT_N',func=pin_types.OPENCOLL),
            Pin(num='10',name='FLIP',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':'R res resistor', 'description':'', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':'cap capacitor', 'description':'', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'CONN_BATT_3P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CONN_BATT_3P'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_JST:JST_ACH_BM03B-ACHSS-GAN-ETF_1x03-1MP_P1.20mm_Vertical', 'keywords':None, 'description':'1S LiPo battery connector (JST-ACH class) + pack NTC', 'datasheet':None, 'pins':[
            Pin(num='1',name='BATT+',func=pin_types.PASSIVE),
            Pin(num='2',name='NTC',func=pin_types.PASSIVE),
            Pin(num='3',name='BATT-',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'BQ29700', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BQ29700'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SON:WSON-6_1.5x1.5mm_P0.5mm', 'keywords':None, 'description':'TI BQ29700 1S Li+ protector (with dual NMOS)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='VSS',func=pin_types.PWRIN),
            Pin(num='3',name='VM',func=pin_types.INPUT),
            Pin(num='4',name='COUT',func=pin_types.OUTPUT),
            Pin(num='5',name='DOUT',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'DUAL_NFET_PROT', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'DUAL_NFET_PROT'}), 'ref_prefix':'Q', 'fplist':None, 'footprint':'Package_SON:WSON-6-1EP_2x2mm_P0.65mm_EP1x1.6mm', 'keywords':None, 'description':'Dual NMOS, battery protection series pair (low-side)', 'datasheet':None, 'pins':[
            Pin(num='1',name='S1',func=pin_types.PASSIVE),
            Pin(num='2',name='G1',func=pin_types.INPUT),
            Pin(num='3',name='D1',func=pin_types.PASSIVE),
            Pin(num='4',name='D2',func=pin_types.PASSIVE),
            Pin(num='5',name='G2',func=pin_types.INPUT),
            Pin(num='6',name='S2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'BQ27427', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BQ27427'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_BGA:Texas_DSBGA-9_1.62mmx1.58mm_Layout3x3_P0.5mm', 'keywords':None, 'description':'TI BQ27427 gauge, SENTINEL_I2C 0x55; low-side sense # VERIFY topology', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='BIN',func=pin_types.INPUT),
            Pin(num='3',name='SRX',func=pin_types.PASSIVE),
            Pin(num='4',name='SDA',func=pin_types.BIDIR),
            Pin(num='5',name='SCL',func=pin_types.BIDIR),
            Pin(num='6',name='GPOUT',func=pin_types.OPENCOLL),
            Pin(num='7',name='VSS',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'BQ25620', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BQ25620'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:Texas_RTE_WQFN-16-1EP_3x3mm_P0.5mm_EP1.2x0.8mm', 'keywords':None, 'description':'TI BQ25620 3.5A charger, ~1C fast charge, SENTINEL_I2C 0x6B', 'datasheet':None, 'pins':[
            Pin(num='1',name='VBUS',func=pin_types.PWRIN),
            Pin(num='2',name='PMID',func=pin_types.PASSIVE),
            Pin(num='3',name='REGN',func=pin_types.PWROUT),
            Pin(num='4',name='SW',func=pin_types.OUTPUT),
            Pin(num='5',name='BTST',func=pin_types.PASSIVE),
            Pin(num='6',name='SYS',func=pin_types.PWROUT),
            Pin(num='7',name='BAT',func=pin_types.PWRIN),
            Pin(num='8',name='SDA',func=pin_types.BIDIR),
            Pin(num='9',name='SCL',func=pin_types.BIDIR),
            Pin(num='10',name='INT_N',func=pin_types.OPENCOLL),
            Pin(num='11',name='CE_N',func=pin_types.INPUT),
            Pin(num='12',name='TS',func=pin_types.INPUT),
            Pin(num='13',name='QON_N',func=pin_types.INPUT),
            Pin(num='14',name='GND',func=pin_types.PWRIN),
            Pin(num='15',name='PGND',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'L', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'L'}), 'ref_prefix':'L', 'fplist':[''], 'footprint':'Inductor_SMD:L_0805_2012Metric', 'keywords':'inductor choke coil reactor magnetic', 'description':'', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TPS62840', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TPS62840'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-583-8', 'keywords':None, 'description':'TI TPS62840, 60nA IQ, always-on 3.3V sentinel rail', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='EN',func=pin_types.INPUT),
            Pin(num='4',name='SW',func=pin_types.OUTPUT),
            Pin(num='5',name='VOS',func=pin_types.INPUT),
            Pin(num='6',name='MODE',func=pin_types.INPUT)] }),
        Part(**{ 'name':'TPS62823', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TPS62823'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-583-8', 'keywords':None, 'description':'TI TPS62823 3A buck', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='EN',func=pin_types.INPUT),
            Pin(num='4',name='SW',func=pin_types.OUTPUT),
            Pin(num='5',name='FB',func=pin_types.INPUT),
            Pin(num='6',name='MODE',func=pin_types.INPUT)] }),
        Part(**{ 'name':'TLV62568', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TLV62568'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':None, 'description':'TI TLV62568 1A buck -> 1V8', 'datasheet':None, 'pins':[
            Pin(num='1',name='EN',func=pin_types.INPUT),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='VIN',func=pin_types.PWRIN),
            Pin(num='4',name='FB',func=pin_types.INPUT),
            Pin(num='5',name='SW',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'TPS22916', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TPS22916'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_CSP:TO_GENERATE_TPS22916_CSP4', 'keywords':None, 'description':'TI TPS22916 load switch (per-domain power gating)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='ON',func=pin_types.INPUT),
            Pin(num='4',name='VOUT',func=pin_types.PWROUT)] }),
        Part(**{ 'name':'STM32N657', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'STM32N657'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_BGA:TO_GENERATE_ST_VFBGA142', 'keywords':None, 'description':'STM32N657X0 app MCU + NPU, VFBGA142 (used-signals model)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD_CORE1',func=pin_types.PWRIN),
            Pin(num='2',name='VDD_CORE2',func=pin_types.PWRIN),
            Pin(num='3',name='VDD18_1',func=pin_types.PWRIN),
            Pin(num='4',name='VDD18_2',func=pin_types.PWRIN),
            Pin(num='5',name='VDD33_1',func=pin_types.PWRIN),
            Pin(num='6',name='VDD33_2',func=pin_types.PWRIN),
            Pin(num='7',name='VDD33_3',func=pin_types.PWRIN),
            Pin(num='8',name='VDD33_4',func=pin_types.PWRIN),
            Pin(num='9',name='VSS1',func=pin_types.PWRIN),
            Pin(num='10',name='VSS2',func=pin_types.PWRIN),
            Pin(num='11',name='VSS3',func=pin_types.PWRIN),
            Pin(num='12',name='VSS4',func=pin_types.PWRIN),
            Pin(num='13',name='SPI1_SCK',func=pin_types.OUTPUT),
            Pin(num='14',name='SPI1_MISO',func=pin_types.INPUT),
            Pin(num='15',name='SPI1_MOSI',func=pin_types.OUTPUT),
            Pin(num='16',name='CS_VL53_N',func=pin_types.OUTPUT),
            Pin(num='17',name='CS_BNO_N',func=pin_types.OUTPUT),
            Pin(num='18',name='CS_ADS_N',func=pin_types.OUTPUT),
            Pin(num='19',name='CS_A121_N',func=pin_types.OUTPUT),
            Pin(num='20',name='I2C1_SCL',func=pin_types.BIDIR),
            Pin(num='21',name='I2C1_SDA',func=pin_types.BIDIR),
            Pin(num='22',name='I2C2_SCL',func=pin_types.BIDIR),
            Pin(num='23',name='I2C2_SDA',func=pin_types.BIDIR),
            Pin(num='24',name='SDIO_CLK',func=pin_types.OUTPUT),
            Pin(num='25',name='SDIO_CMD',func=pin_types.BIDIR),
            Pin(num='26',name='SDIO_D0',func=pin_types.BIDIR),
            Pin(num='27',name='SDIO_D1',func=pin_types.BIDIR),
            Pin(num='28',name='SDIO_D2',func=pin_types.BIDIR),
            Pin(num='29',name='SDIO_D3',func=pin_types.BIDIR),
            Pin(num='30',name='UART1_TX',func=pin_types.OUTPUT),
            Pin(num='31',name='UART1_RX',func=pin_types.INPUT),
            Pin(num='32',name='PPS_IN',func=pin_types.INPUT),
            Pin(num='33',name='UART2_TX',func=pin_types.OUTPUT),
            Pin(num='34',name='UART2_RX',func=pin_types.INPUT),
            Pin(num='35',name='USB_DP',func=pin_types.BIDIR),
            Pin(num='36',name='USB_DM',func=pin_types.BIDIR),
            Pin(num='37',name='CSI_CKP',func=pin_types.BIDIR),
            Pin(num='38',name='CSI_CKN',func=pin_types.BIDIR),
            Pin(num='39',name='CSI_D0P',func=pin_types.BIDIR),
            Pin(num='40',name='CSI_D0N',func=pin_types.BIDIR),
            Pin(num='41',name='CSI_D1P',func=pin_types.BIDIR),
            Pin(num='42',name='CSI_D1N',func=pin_types.BIDIR),
            Pin(num='43',name='CAM_XCLK',func=pin_types.OUTPUT),
            Pin(num='44',name='CAM_RSTN',func=pin_types.OUTPUT),
            Pin(num='45',name='PDM_CLK',func=pin_types.OUTPUT),
            Pin(num='46',name='PDM_DATA',func=pin_types.INPUT),
            Pin(num='47',name='ADC_IN0',func=pin_types.INPUT),
            Pin(num='48',name='MCO_OUT',func=pin_types.OUTPUT),
            Pin(num='49',name='SWDIO',func=pin_types.BIDIR),
            Pin(num='50',name='SWCLK',func=pin_types.INPUT),
            Pin(num='51',name='NRST',func=pin_types.INPUT),
            Pin(num='52',name='BOOT0',func=pin_types.INPUT),
            Pin(num='53',name='XSPI_D0',func=pin_types.BIDIR),
            Pin(num='54',name='XSPI_D1',func=pin_types.BIDIR),
            Pin(num='55',name='XSPI_D2',func=pin_types.BIDIR),
            Pin(num='56',name='XSPI_D3',func=pin_types.BIDIR),
            Pin(num='57',name='XSPI_D4',func=pin_types.BIDIR),
            Pin(num='58',name='XSPI_D5',func=pin_types.BIDIR),
            Pin(num='59',name='XSPI_D6',func=pin_types.BIDIR),
            Pin(num='60',name='XSPI_D7',func=pin_types.BIDIR),
            Pin(num='61',name='XSPI_CLK',func=pin_types.OUTPUT),
            Pin(num='62',name='XSPI_CS_N',func=pin_types.OUTPUT),
            Pin(num='63',name='XSPI_DQS',func=pin_types.BIDIR),
            Pin(num='64',name='INT_VL53',func=pin_types.INPUT),
            Pin(num='65',name='INT_BNO',func=pin_types.INPUT),
            Pin(num='66',name='DRDY_ADS',func=pin_types.INPUT),
            Pin(num='67',name='INT_MAX',func=pin_types.INPUT),
            Pin(num='68',name='INT_AS7058',func=pin_types.INPUT),
            Pin(num='69',name='IRQ_A121',func=pin_types.INPUT),
            Pin(num='70',name='DRDY_MMC',func=pin_types.INPUT),
            Pin(num='71',name='INT_TMAG',func=pin_types.INPUT),
            Pin(num='72',name='INT_TCS',func=pin_types.INPUT),
            Pin(num='73',name='RDY_AS7331',func=pin_types.INPUT),
            Pin(num='74',name='INT_AS7421',func=pin_types.INPUT),
            Pin(num='75',name='INT_BMV',func=pin_types.INPUT),
            Pin(num='76',name='INT_ENS',func=pin_types.INPUT),
            Pin(num='77',name='WAKE_IN',func=pin_types.INPUT),
            Pin(num='78',name='WAKE_OUT',func=pin_types.OUTPUT),
            Pin(num='79',name='EN_UV_REQ',func=pin_types.OUTPUT),
            Pin(num='80',name='EN_WHITE',func=pin_types.OUTPUT),
            Pin(num='81',name='RSTN_BNO',func=pin_types.OUTPUT),
            Pin(num='82',name='LPN_VL53',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'NOR_OCTAL_XSPI', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'NOR_OCTAL_XSPI'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_BGA:TO_GENERATE_NOR_BGA24_5x5', 'keywords':None, 'description':'Octal xSPI NOR flash for STM32N657 (MX25UW6445G-class)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VCC',func=pin_types.PWRIN),
            Pin(num='2',name='VSS',func=pin_types.PWRIN),
            Pin(num='3',name='CS_N',func=pin_types.INPUT),
            Pin(num='4',name='CLK',func=pin_types.INPUT),
            Pin(num='5',name='DQS',func=pin_types.OUTPUT),
            Pin(num='6',name='RESET_N',func=pin_types.INPUT),
            Pin(num='7',name='DQ0',func=pin_types.BIDIR),
            Pin(num='8',name='DQ1',func=pin_types.BIDIR),
            Pin(num='9',name='DQ2',func=pin_types.BIDIR),
            Pin(num='10',name='DQ3',func=pin_types.BIDIR),
            Pin(num='11',name='DQ4',func=pin_types.BIDIR),
            Pin(num='12',name='DQ5',func=pin_types.BIDIR),
            Pin(num='13',name='DQ6',func=pin_types.BIDIR),
            Pin(num='14',name='DQ7',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'BL54L15', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BL54L15'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'RF_Module:TO_GENERATE_BL54L15', 'keywords':None, 'description':'Ezurio BL54L15 (nRF54L15) BLE sentinel module', 'datasheet':None, 'pins':[
            Pin(num='1',name='VCC',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SENT_SCL',func=pin_types.BIDIR),
            Pin(num='4',name='SENT_SDA',func=pin_types.BIDIR),
            Pin(num='5',name='GEIGER_PULSE_IN',func=pin_types.INPUT),
            Pin(num='6',name='EN_OPTICAL',func=pin_types.OUTPUT),
            Pin(num='7',name='EN_AIR',func=pin_types.OUTPUT),
            Pin(num='8',name='EN_CONTACT',func=pin_types.OUTPUT),
            Pin(num='9',name='EN_RADAR',func=pin_types.OUTPUT),
            Pin(num='10',name='EN_GNSS',func=pin_types.OUTPUT),
            Pin(num='11',name='EN_WIFI',func=pin_types.OUTPUT),
            Pin(num='12',name='EN_N6',func=pin_types.OUTPUT),
            Pin(num='13',name='EN_FAN',func=pin_types.OUTPUT),
            Pin(num='14',name='EN_ACC',func=pin_types.OUTPUT),
            Pin(num='15',name='EN_HAPTIC',func=pin_types.OUTPUT),
            Pin(num='16',name='INTERLOCK_OK',func=pin_types.OUTPUT),
            Pin(num='17',name='UART_TX',func=pin_types.OUTPUT),
            Pin(num='18',name='UART_RX',func=pin_types.INPUT),
            Pin(num='19',name='WAKE_N6',func=pin_types.OUTPUT),
            Pin(num='20',name='ATTN_FROM_N6',func=pin_types.INPUT),
            Pin(num='21',name='TOUCH_RDY_IN',func=pin_types.INPUT),
            Pin(num='22',name='GAUGE_INT_IN',func=pin_types.INPUT),
            Pin(num='23',name='CHG_INT_IN',func=pin_types.INPUT),
            Pin(num='24',name='GLOW1',func=pin_types.OUTPUT),
            Pin(num='25',name='GLOW2',func=pin_types.OUTPUT),
            Pin(num='26',name='GLOW3',func=pin_types.OUTPUT),
            Pin(num='27',name='GLOW4',func=pin_types.OUTPUT),
            Pin(num='28',name='GLOW5',func=pin_types.OUTPUT),
            Pin(num='29',name='GLOW6',func=pin_types.OUTPUT),
            Pin(num='30',name='NFC1',func=pin_types.NOCONNECT),
            Pin(num='31',name='NFC2',func=pin_types.NOCONNECT),
            Pin(num='32',name='SWDIO',func=pin_types.BIDIR),
            Pin(num='33',name='SWCLK',func=pin_types.INPUT),
            Pin(num='34',name='RESET_N',func=pin_types.INPUT)] }),
        Part(**{ 'name':'ESP32-C6-MINI-1/U', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ESP32-C6-MINI-1/U'}), 'ref_prefix':'U', 'fplist':['PCM_Espressif:ESP32-C6-MINI-1'], 'footprint':'Espressif:ESP32-C6-MINI-1', 'keywords':'esp32-c6 esp32-c6-mini-1 esp32-c6-mini-1u', 'description':'ESP32-C6-MINI-1 is a module that supports 2.4 GHz Wi-Fi 6 (802.11 ax), BluetoothÂ® 5 (LE), Zigbee and Thread (802.15.4)', 'datasheet':'https://www.espressif.com/sites/default/files/documentation/esp32-c6-mini-1_datasheet_en.pdf', 'pins':[
            Pin(num='8',name='EN/CHIP_PU',func=pin_types.INPUT,unit=1),
            Pin(num='12',name='GPIO0/ADC1_CH0/XTAL_32K_P',func=pin_types.BIDIR,unit=1),
            Pin(num='13',name='GPIO1/ADC1_CH1/XTAL_32K_N',func=pin_types.BIDIR,unit=1),
            Pin(num='5',name='GPIO2/ADC1_CH2',func=pin_types.BIDIR,unit=1),
            Pin(num='6',name='GPIO3/ADC1_CH3',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='MTMS/GPIO4/ADC1_CH4',func=pin_types.BIDIR,unit=1),
            Pin(num='10',name='MTDI/GPIO5/ADC1_CH5',func=pin_types.BIDIR,unit=1),
            Pin(num='15',name='MTCK/GPIO6/ADC1_CH6',func=pin_types.BIDIR,unit=1),
            Pin(num='16',name='MTDO/GPIO7',func=pin_types.BIDIR,unit=1),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='7',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='21',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='32',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='33',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='34',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='35',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='3',name='3V3',func=pin_types.PWRIN,unit=1),
            Pin(num='1',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='11',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='36',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='37',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='38',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='39',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='40',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='41',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='42',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='43',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='44',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='45',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='46',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='47',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='48',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='49',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='50',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='51',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='52',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='53',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='31',name='U0TXD/GPIO16',func=pin_types.BIDIR,unit=1),
            Pin(num='30',name='U0RXD/GPIO17',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='GPIO13/USB_D+',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='GPIO12/USB_D-',func=pin_types.BIDIR,unit=1),
            Pin(num='22',name='GPIO8',func=pin_types.BIDIR,unit=1),
            Pin(num='23',name='GPIO9',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='GPIO14',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='GPIO15',func=pin_types.BIDIR,unit=1),
            Pin(num='24',name='GPIO18',func=pin_types.BIDIR,unit=1),
            Pin(num='25',name='GPIO19',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='GPIO20',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='GPIO21',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='GPIO22',func=pin_types.BIDIR,unit=1),
            Pin(num='29',name='GPIO23',func=pin_types.BIDIR,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'VL53L8CH', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'VL53L8CH'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Sensor_Distance:TO_GENERATE_ST_VL53L8', 'keywords':None, 'description':'ST VL53L8CH 8x8 ToF, SPI mode (straps in copper)', 'datasheet':None, 'pins':[
            Pin(num='1',name='AVDD',func=pin_types.PWRIN),
            Pin(num='2',name='IOVDD',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='SCLK',func=pin_types.INPUT),
            Pin(num='5',name='MOSI',func=pin_types.INPUT),
            Pin(num='6',name='MISO',func=pin_types.TRISTATE),
            Pin(num='7',name='NCS',func=pin_types.INPUT),
            Pin(num='8',name='SPI_I2C_N',func=pin_types.INPUT),
            Pin(num='9',name='I2C_RST',func=pin_types.INPUT),
            Pin(num='10',name='LPN',func=pin_types.INPUT),
            Pin(num='11',name='INT',func=pin_types.OPENCOLL)] }),
        Part(**{ 'name':'BNO086', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BNO086'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_LGA:LGA-28_5.2x3.8mm_P0.5mm', 'keywords':None, 'description':'CEVA/Bosch BNO086 IMU, SPI mode, raw+fused', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='VDDIO',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='PS0_WAKE',func=pin_types.INPUT),
            Pin(num='5',name='PS1',func=pin_types.INPUT),
            Pin(num='6',name='H_CSN',func=pin_types.INPUT),
            Pin(num='7',name='H_SCLK',func=pin_types.INPUT),
            Pin(num='8',name='H_MOSI',func=pin_types.INPUT),
            Pin(num='9',name='H_MISO',func=pin_types.TRISTATE),
            Pin(num='10',name='H_INTN',func=pin_types.OPENCOLL),
            Pin(num='11',name='NRST',func=pin_types.INPUT),
            Pin(num='12',name='BOOTN',func=pin_types.INPUT)] }),
        Part(**{ 'name':'ADS131M04', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ADS131M04'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:TO_GENERATE_TI_ADS131M04_WQFN20', 'keywords':None, 'description':'TI ADS131M04 4ch 24b simultaneous ADC (piezo + PIN + spares)', 'datasheet':None, 'pins':[
            Pin(num='1',name='AVDD',func=pin_types.PWRIN),
            Pin(num='2',name='DVDD',func=pin_types.PWRIN),
            Pin(num='3',name='AGND',func=pin_types.PWRIN),
            Pin(num='4',name='DGND',func=pin_types.PWRIN),
            Pin(num='5',name='AIN0P',func=pin_types.INPUT),
            Pin(num='6',name='AIN0N',func=pin_types.INPUT),
            Pin(num='7',name='AIN1P',func=pin_types.INPUT),
            Pin(num='8',name='AIN1N',func=pin_types.INPUT),
            Pin(num='9',name='AIN2P',func=pin_types.INPUT),
            Pin(num='10',name='AIN2N',func=pin_types.INPUT),
            Pin(num='11',name='AIN3P',func=pin_types.INPUT),
            Pin(num='12',name='AIN3N',func=pin_types.INPUT),
            Pin(num='13',name='SCLK',func=pin_types.INPUT),
            Pin(num='14',name='DIN',func=pin_types.INPUT),
            Pin(num='15',name='DOUT',func=pin_types.TRISTATE),
            Pin(num='16',name='CS_N',func=pin_types.INPUT),
            Pin(num='17',name='DRDY_N',func=pin_types.OUTPUT),
            Pin(num='18',name='SYNC_RESET_N',func=pin_types.INPUT),
            Pin(num='19',name='CLKIN',func=pin_types.INPUT)] }),
        Part(**{ 'name':'PIEZO', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PIEZO'}), 'ref_prefix':'PZ', 'fplist':None, 'footprint':'TO_GENERATE:PIEZO_DISC_PADS', 'keywords':None, 'description':'Piezo disc, contact vibration -> ADS131M04 AIN0 diff', 'datasheet':None, 'pins':[
            Pin(num='1',name='P1',func=pin_types.PASSIVE),
            Pin(num='2',name='P2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'MLX90642', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MLX90642'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_THT:TO-39-4', 'keywords':None, 'description':'Melexis MLX90642 32x24 FIR array, TO-39, I2C-A 0x33', 'datasheet':None, 'pins':[
            Pin(num='1',name='SDA',func=pin_types.BIDIR),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='VDD',func=pin_types.PWRIN),
            Pin(num='4',name='SCL',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'MLX90632', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MLX90632'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:TO_GENERATE_MLX90632_SFN', 'keywords':None, 'description':'Melexis MLX90632 medical spot FIR, I2C-A 0x3A', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='SCL',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'MAX30102', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MAX30102'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'OptoDevice:Maxim_OLGA-14_3.3x5.6mm_P0.8mm', 'keywords':None, 'description':'MAX30102 PPG, I2C-A 0x57; VDD=1V8, VLED=3V3_CONTACT', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='VLED_P',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='PGND',func=pin_types.PWRIN),
            Pin(num='5',name='SDA',func=pin_types.BIDIR),
            Pin(num='6',name='SCL',func=pin_types.BIDIR),
            Pin(num='7',name='INT_N',func=pin_types.OPENCOLL)] }),
        Part(**{ 'name':'AS7058', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AS7058'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_CSP:TO_GENERATE_AS7058_WLCSP42', 'keywords':None, 'description':'ams AS7058 PPG/ECG/BioZ AFE, I2C-A 0x30 # VERIFY addr', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='VDDIO',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='SCL',func=pin_types.BIDIR),
            Pin(num='5',name='SDA',func=pin_types.BIDIR),
            Pin(num='6',name='INT',func=pin_types.OUTPUT),
            Pin(num='7',name='ECG_INP',func=pin_types.INPUT),
            Pin(num='8',name='ECG_INN',func=pin_types.INPUT),
            Pin(num='9',name='ECG_REF',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'ELECTRODE', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ELECTRODE'}), 'ref_prefix':'E', 'fplist':None, 'footprint':'TO_GENERATE:ELECTRODE_FIELD', 'keywords':None, 'description':'Exposed electrode pad (ECG contact / return)', 'datasheet':None, 'pins':[
            Pin(num='1',name='E',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'BME688', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BME688'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_LGA:Bosch_LGA-8_3x3mm_P0.8mm_ClockwisePinNumbering', 'keywords':None, 'description':'Bosch BME688 gas/T/RH/P, I2C-B 0x77 (SDO=1)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='VDDIO',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='SCK',func=pin_types.BIDIR),
            Pin(num='5',name='SDI',func=pin_types.BIDIR),
            Pin(num='6',name='SDO',func=pin_types.INPUT),
            Pin(num='7',name='CSB',func=pin_types.INPUT)] }),
        Part(**{ 'name':'SGP41', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SGP41'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Sensor_Humidity:TO_GENERATE_SGP41_DFN', 'keywords':None, 'description':'Sensirion SGP41 VOC/NOx, I2C-B 0x59 (fixed)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='SCL',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'ENS161', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ENS161'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_LGA:TO_GENERATE_ENS161_LGA9', 'keywords':None, 'description':'ScioSense ENS161 4-el MOX, I2C-B 0x53; VDD=1V8', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='VDDIO',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='SDA',func=pin_types.BIDIR),
            Pin(num='5',name='SCL',func=pin_types.BIDIR),
            Pin(num='6',name='ADDR',func=pin_types.INPUT),
            Pin(num='7',name='INT_N',func=pin_types.OUTPUT),
            Pin(num='8',name='CS_N',func=pin_types.INPUT)] }),
        Part(**{ 'name':'SCD41', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SCD41'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Sensor:Sensirion_SCD4x-1EP_10.1x10.1mm_P1.25mm_EP4.8x4.8mm', 'keywords':None, 'description':'Sensirion SCD41 photoacoustic CO2, I2C-B 0x62 (fixed)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='SCL',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'SHT41', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SHT41'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Sensor_Humidity:Sensirion_DFN-4_1.5x1.5mm_P0.8mm_SHT4x_NoCentralPad', 'keywords':None, 'description':'Sensirion SHT41 ref T/RH, I2C-B 0x44 (fixed)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='SCL',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'TCS3448', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TCS3448'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'OptoDevice:TO_GENERATE_TCS3448_OLGA', 'keywords':None, 'description':'ams TCS3448 14ch VIS spectral, I2C-B 0x39 # VERIFY addr', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='SCL',func=pin_types.BIDIR),
            Pin(num='5',name='INT_N',func=pin_types.OPENCOLL)] }),
        Part(**{ 'name':'AS7331', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AS7331'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'OptoDevice:TO_GENERATE_AS7331_OLGA16', 'keywords':None, 'description':'ams AS7331 UV A/B/C, I2C-B 0x74 (A1A0=00)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='SCL',func=pin_types.BIDIR),
            Pin(num='5',name='A0',func=pin_types.INPUT),
            Pin(num='6',name='A1',func=pin_types.INPUT),
            Pin(num='7',name='READY',func=pin_types.OUTPUT),
            Pin(num='8',name='SYN',func=pin_types.INPUT)] }),
        Part(**{ 'name':'AS7421', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AS7421'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'OptoDevice:TO_GENERATE_AS7421_OLGA', 'keywords':None, 'description':'ams AS7421 64ch NIR, I2C-B 0x64 # VERIFY addr', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='SCL',func=pin_types.BIDIR),
            Pin(num='5',name='INT',func=pin_types.OPENCOLL),
            Pin(num='6',name='LED0',func=pin_types.OPENCOLL)] }),
        Part(**{ 'name':'LED', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':'LED diode', 'description':'', 'datasheet':'~', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'MMC5983MA', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MMC5983MA'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_LGA:LGA-16_3x3mm_P0.5mm', 'keywords':None, 'description':'Memsic MMC5983MA nT mag, I2C-B 0x30', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='VDDIO',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='SDA',func=pin_types.BIDIR),
            Pin(num='5',name='SCL',func=pin_types.BIDIR),
            Pin(num='6',name='INT_DRDY',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'TMAG5273', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TMAG5273'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':None, 'description':'TI TMAG5273A1 hall, I2C-B 0x35 # VERIFY variant/addr', 'datasheet':None, 'pins':[
            Pin(num='1',name='SCL',func=pin_types.BIDIR),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='INT_N',func=pin_types.OPENCOLL),
            Pin(num='5',name='VCC',func=pin_types.PWRIN),
            Pin(num='6',name='NC',func=pin_types.NOCONNECT)] }),
        Part(**{ 'name':'BMV080', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BMV080'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Sensor:TO_GENERATE_BMV080', 'keywords':None, 'description':'Bosch BMV080 PM2.5, I2C-B 0x57 # VERIFY addr', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='VDDIO',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='SDA',func=pin_types.BIDIR),
            Pin(num='5',name='SCL',func=pin_types.BIDIR),
            Pin(num='6',name='IRQ',func=pin_types.OUTPUT),
            Pin(num='7',name='AB_SEL',func=pin_types.INPUT)] }),
        Part(**{ 'name':'A121', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'A121'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_CSP:TO_GENERATE_A121_FCCSP', 'keywords':None, 'description':'Acconeer A121 pulsed coherent radar, Sparse-IQ raw', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIO1',func=pin_types.PWRIN),
            Pin(num='2',name='VIO2',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='SPI_SCLK',func=pin_types.INPUT),
            Pin(num='5',name='SPI_MOSI',func=pin_types.INPUT),
            Pin(num='6',name='SPI_MISO',func=pin_types.TRISTATE),
            Pin(num='7',name='SPI_SS_N',func=pin_types.INPUT),
            Pin(num='8',name='INTERRUPT',func=pin_types.OUTPUT),
            Pin(num='9',name='ENABLE',func=pin_types.INPUT)] }),
        Part(**{ 'name':'MIA_M10Q', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MIA_M10Q'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'RF_GPS:TO_GENERATE_UBLOX_MIA_M10Q', 'keywords':None, 'description':'u-blox MIA-M10Q GNSS (RAWX), UART + PPS', 'datasheet':None, 'pins':[
            Pin(num='1',name='VCC',func=pin_types.PWRIN),
            Pin(num='2',name='V_BCKP',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='TXD',func=pin_types.OUTPUT),
            Pin(num='5',name='RXD',func=pin_types.INPUT),
            Pin(num='6',name='TIMEPULSE',func=pin_types.OUTPUT),
            Pin(num='7',name='RF_IN',func=pin_types.INPUT)] }),
        Part(**{ 'name':'D_Schottky', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D_Schottky'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'Diode_SMD:D_SOD-323', 'keywords':'diode Schottky', 'description':'', 'datasheet':'~', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'ANT_GNSS', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ANT_GNSS'}), 'ref_prefix':'AE', 'fplist':None, 'footprint':'RF_Antenna:TO_GENERATE_GNSS_CHIP_ANT', 'keywords':None, 'description':'GNSS L1 chip antenna (keepout corner)', 'datasheet':None, 'pins':[
            Pin(num='1',name='FEED',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'PDM_MIC', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PDM_MIC'}), 'ref_prefix':'MK', 'fplist':None, 'footprint':'Sensor_Audio:Knowles_LGA-5_3.5x2.65mm', 'keywords':None, 'description':'MEMS PDM mic, bottom port (heart/lung + acoustic)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='CLK',func=pin_types.INPUT),
            Pin(num='4',name='DATA',func=pin_types.TRISTATE),
            Pin(num='5',name='SEL',func=pin_types.INPUT)] }),
        Part(**{ 'name':'CONN_FPC_24P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CONN_FPC_24P'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_FFC-FPC:TO_GENERATE_FPC24_0.5mm', 'keywords':None, 'description':'24p FPC, VD66GY camera (MIPI CSI-2) — DNP in v1', 'datasheet':None, 'pins':[
            Pin(num='1',name='P1',func=pin_types.PASSIVE),
            Pin(num='2',name='P2',func=pin_types.PASSIVE),
            Pin(num='3',name='P3',func=pin_types.PASSIVE),
            Pin(num='4',name='P4',func=pin_types.PASSIVE),
            Pin(num='5',name='P5',func=pin_types.PASSIVE),
            Pin(num='6',name='P6',func=pin_types.PASSIVE),
            Pin(num='7',name='P7',func=pin_types.PASSIVE),
            Pin(num='8',name='P8',func=pin_types.PASSIVE),
            Pin(num='9',name='P9',func=pin_types.PASSIVE),
            Pin(num='10',name='P10',func=pin_types.PASSIVE),
            Pin(num='11',name='P11',func=pin_types.PASSIVE),
            Pin(num='12',name='P12',func=pin_types.PASSIVE),
            Pin(num='13',name='P13',func=pin_types.PASSIVE),
            Pin(num='14',name='P14',func=pin_types.PASSIVE),
            Pin(num='15',name='P15',func=pin_types.PASSIVE),
            Pin(num='16',name='P16',func=pin_types.PASSIVE),
            Pin(num='17',name='P17',func=pin_types.PASSIVE),
            Pin(num='18',name='P18',func=pin_types.PASSIVE),
            Pin(num='19',name='P19',func=pin_types.PASSIVE),
            Pin(num='20',name='P20',func=pin_types.PASSIVE),
            Pin(num='21',name='P21',func=pin_types.PASSIVE),
            Pin(num='22',name='P22',func=pin_types.PASSIVE),
            Pin(num='23',name='P23',func=pin_types.PASSIVE),
            Pin(num='24',name='P24',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'PIN_BPW34', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PIN_BPW34'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'OptoDevice:Osram_BPW34S-SMD', 'keywords':None, 'description':'BPW34S-class large-area PIN photodiode, light-tight cavity', 'datasheet':None, 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE),
            Pin(num='2',name='K',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'OPA381', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'OPA381'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:TO_GENERATE_OPA381_MSOP8', 'keywords':None, 'description':'OPA381-class transimpedance/charge amp for PIN detector', 'datasheet':None, 'pins':[
            Pin(num='1',name='V+',func=pin_types.PWRIN),
            Pin(num='2',name='V-',func=pin_types.PWRIN),
            Pin(num='3',name='+IN',func=pin_types.INPUT),
            Pin(num='4',name='-IN',func=pin_types.INPUT),
            Pin(num='5',name='OUT',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'TLV3201', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TLV3201'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':None, 'description':'TLV3201-class comparator -> GEIGER_PULSE counting', 'datasheet':None, 'pins':[
            Pin(num='1',name='V+',func=pin_types.PWRIN),
            Pin(num='2',name='V-',func=pin_types.PWRIN),
            Pin(num='3',name='+IN',func=pin_types.INPUT),
            Pin(num='4',name='-IN',func=pin_types.INPUT),
            Pin(num='5',name='OUT',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'SHIELD_CAN', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SHIELD_CAN'}), 'ref_prefix':'SH', 'fplist':None, 'footprint':'TO_GENERATE:SHIELD_CAN_RAD', 'keywords':None, 'description':'Shield can, radiation charge-amp cavity (light-tight)', 'datasheet':None, 'pins':[
            Pin(num='1',name='S1',func=pin_types.PASSIVE),
            Pin(num='2',name='S2',func=pin_types.PASSIVE),
            Pin(num='3',name='S3',func=pin_types.PASSIVE),
            Pin(num='4',name='S4',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'AD8317', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AD8317'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:TO_GENERATE_AD8317_LFCSP8', 'keywords':None, 'description':'AD8317 1M-10GHz RF power detector -> N657 ADC_IN0', 'datasheet':None, 'pins':[
            Pin(num='1',name='VPOS',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='INHI',func=pin_types.INPUT),
            Pin(num='4',name='INLO',func=pin_types.INPUT),
            Pin(num='5',name='VOUT',func=pin_types.OUTPUT),
            Pin(num='6',name='TADJ',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SMA_EDGE', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SMA_EDGE'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_Coaxial:SMA_Amphenol_132134_Vertical', 'keywords':None, 'description':'SMA, RF survey input -> AD8317', 'datasheet':None, 'pins':[
            Pin(num='1',name='SIG',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'74LVC1G08', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'74LVC1G08'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-353_SC-70-5', 'keywords':None, 'description':'Single AND: EN_UV_REQ & INTERLOCK_OK -> UV LED gate (R5)', 'datasheet':None, 'pins':[
            Pin(num='1',name='A',func=pin_types.INPUT),
            Pin(num='2',name='B',func=pin_types.INPUT),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='Y',func=pin_types.OUTPUT),
            Pin(num='5',name='VCC',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'NFET_SOT23', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'NFET_SOT23'}), 'ref_prefix':'Q', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':None, 'description':'N-ch FET, SOT-23 (LED / fan low-side drive)', 'datasheet':None, 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT),
            Pin(num='2',name='S',func=pin_types.PASSIVE),
            Pin(num='3',name='D',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'CONN_FAN_2P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CONN_FAN_2P'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_PinHeader_1.00mm:PinHeader_1x02_P1.00mm_Vertical_SMD_Pin1Left', 'keywords':None, 'description':'Blower fan (Sunon UB3F3-500 class), low-side switched', 'datasheet':None, 'pins':[
            Pin(num='1',name='FAN+',func=pin_types.PWRIN),
            Pin(num='2',name='FAN-',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SGX_4CO', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SGX_4CO'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'TO_GENERATE:SGX_4CO_4SERIES_TH', 'keywords':None, 'description':'SGX 4-CO electrochemical CO cell (serviceable, R2 flag)', 'datasheet':None, 'pins':[
            Pin(num='1',name='WE',func=pin_types.PASSIVE),
            Pin(num='2',name='RE',func=pin_types.PASSIVE),
            Pin(num='3',name='CE',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'LMP91000', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LMP91000'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:TO_GENERATE_LMP91000_WSON14', 'keywords':None, 'description':'LMP91000 potentiostat, I2C-B 0x48 (fixed) -> ADS AIN3', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='SCL',func=pin_types.BIDIR),
            Pin(num='5',name='MENB_N',func=pin_types.INPUT),
            Pin(num='6',name='VOUT',func=pin_types.OUTPUT),
            Pin(num='7',name='C1',func=pin_types.PASSIVE),
            Pin(num='8',name='C2',func=pin_types.PASSIVE),
            Pin(num='9',name='WE',func=pin_types.PASSIVE),
            Pin(num='10',name='RE',func=pin_types.PASSIVE),
            Pin(num='11',name='CE',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'CONN_POGO_6P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CONN_POGO_6P'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector:TO_GENERATE_POGO6_MAGRING', 'keywords':None, 'description':'Magnetic 6-pogo accessory port (ADR-0002): pwr+I2C-ID+2 analog', 'datasheet':None, 'pins':[
            Pin(num='1',name='VACC',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='SCL',func=pin_types.BIDIR),
            Pin(num='5',name='AN1',func=pin_types.PASSIVE),
            Pin(num='6',name='AN2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'IQS7222A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'IQS7222A'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:QFN-20-1EP_3x3mm_P0.4mm_EP1.65x1.65mm', 'keywords':None, 'description':'Azoteq IQS7222A touch, SENTINEL_I2C 0x44 (deliberate: avoids SHT41 0x44 on I2C-B)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDDHI',func=pin_types.PWRIN),
            Pin(num='2',name='VREG',func=pin_types.PASSIVE),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='SDA',func=pin_types.BIDIR),
            Pin(num='5',name='SCL',func=pin_types.BIDIR),
            Pin(num='6',name='RDY',func=pin_types.OPENCOLL),
            Pin(num='7',name='MCLR_N',func=pin_types.INPUT),
            Pin(num='8',name='E0',func=pin_types.PASSIVE),
            Pin(num='9',name='E1',func=pin_types.PASSIVE),
            Pin(num='10',name='E2',func=pin_types.PASSIVE),
            Pin(num='11',name='E3',func=pin_types.PASSIVE),
            Pin(num='12',name='E4',func=pin_types.PASSIVE),
            Pin(num='13',name='E5',func=pin_types.PASSIVE),
            Pin(num='14',name='E6',func=pin_types.PASSIVE),
            Pin(num='15',name='E7',func=pin_types.PASSIVE),
            Pin(num='16',name='E8',func=pin_types.PASSIVE),
            Pin(num='17',name='E9',func=pin_types.PASSIVE),
            Pin(num='18',name='E10',func=pin_types.PASSIVE),
            Pin(num='19',name='E11',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'CONN_TOUCH_13P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CONN_TOUCH_13P'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_FFC-FPC:TO_GENERATE_FPC13_0.5mm', 'keywords':None, 'description':'Shell touch-electrode flex, 12 electrodes + guard GND', 'datasheet':None, 'pins':[
            Pin(num='1',name='E0',func=pin_types.PASSIVE),
            Pin(num='2',name='E1',func=pin_types.PASSIVE),
            Pin(num='3',name='E2',func=pin_types.PASSIVE),
            Pin(num='4',name='E3',func=pin_types.PASSIVE),
            Pin(num='5',name='E4',func=pin_types.PASSIVE),
            Pin(num='6',name='E5',func=pin_types.PASSIVE),
            Pin(num='7',name='E6',func=pin_types.PASSIVE),
            Pin(num='8',name='E7',func=pin_types.PASSIVE),
            Pin(num='9',name='E8',func=pin_types.PASSIVE),
            Pin(num='10',name='E9',func=pin_types.PASSIVE),
            Pin(num='11',name='E10',func=pin_types.PASSIVE),
            Pin(num='12',name='E11',func=pin_types.PASSIVE),
            Pin(num='13',name='GND',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'DRV2605L', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'DRV2605L'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:VSSOP-10_3x3mm_P0.5mm', 'keywords':None, 'description':'TI DRV2605L LRA driver, SENTINEL_I2C 0x5A', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='SDA',func=pin_types.BIDIR),
            Pin(num='4',name='SCL',func=pin_types.BIDIR),
            Pin(num='5',name='EN',func=pin_types.INPUT),
            Pin(num='6',name='IN_TRIG',func=pin_types.INPUT),
            Pin(num='7',name='OUT_P',func=pin_types.OUTPUT),
            Pin(num='8',name='OUT_N',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'CONN_LRA_2P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CONN_LRA_2P'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'TO_GENERATE:LRA_PADS', 'keywords':None, 'description':'LRA haptic actuator pads', 'datasheet':None, 'pins':[
            Pin(num='1',name='OUT+',func=pin_types.PASSIVE),
            Pin(num='2',name='OUT-',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'TC2030', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TC2030'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector:Tag-Connect_TC2030-IDC-NL_2x03_P1.27mm_Vertical', 'keywords':None, 'description':'Tag-Connect TC2030-IDC-NL SWD footprint (no BOM cost)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VTREF',func=pin_types.PWRIN),
            Pin(num='2',name='SWDIO',func=pin_types.BIDIR),
            Pin(num='3',name='NRST',func=pin_types.PASSIVE),
            Pin(num='4',name='SWCLK',func=pin_types.PASSIVE),
            Pin(num='5',name='GND',func=pin_types.PWRIN),
            Pin(num='6',name='SWO',func=pin_types.PASSIVE)] })])