#!/usr/bin/env python3
"""Netlist -> .kicad_pcb via the pcbnew python bindings (KiCad 7.0.11).

H3.2 rebuild — placement-true and fully bound. The two H2 debts are closed
structurally (violations are BUILD FAILURES, not stats):

  * ZERO overlap-fallback placements: the 41 components.json majors land at
    their packed x/y/side (+ per-ref rotation), and every remaining part is
    placed by an anchor-driven spiral placer (nearest free courtyard-clear
    cell to the weighted centroid of its already-placed net neighbours,
    trying both 0/90 rotations). If any part cannot be placed collision-free
    inside the bean, the build EXITS 1 — fix design_v1.py and repack.
  * ZERO undeclared unbound pads: every pad must be either (a) bound to its
    net from interrogator_v1.net, (b) listed in nc_pins.json (the SKiDL
    no-connect ledger generated by circuit/main.py — every entry justified
    at the model in lib_parts.py), or (c) an unnumbered mechanical/paste
    pad (pad number "" — NPTH holes and EP paste apertures in the official
    libs). Anything else EXITS 1.

Also here (H3.2 scope):
  * BL54L15 slid flush to the +y smooth rim, antenna end outboard, so the
    5.0x8.5 antenna keep-out extension is off-board air (EZ-DS v1.9 §7.3.1).
  * AE_GNSS (SR4G013) placed at the reserved fat-notch RF corner next to
    the MIA-M10Q's RF_IN corner.
  * 6-layer stack (JLCPCB 6L through-via + POFV), default netclass
    0.1/0.1; PWR / diff-pair / RF netclasses seeded into the committed
    .kicad_pro (patterns + placeholder geometry for H3.3); the VFBGA142
    fanout area rule (0.09/0.09) lives in interrogator_v1.kicad_dru.

Placement here is still a ROUTING BASELINE, not a reviewed layout.
Run: python3 boards/v1/board/build_board.py
"""
import json
import math
import re
import sys
from pathlib import Path

import numpy as np
import pcbnew
from shapely.geometry import LineString, Point, Polygon

HERE = Path(__file__).resolve().parent          # boards/v1/board
V1 = HERE.parent
REPO = V1.parents[1]
LIB = REPO / "library" / "footprints"
OFFICIAL = Path("/usr/share/kicad/footprints")

NETLIST = V1 / "netlist" / "interrogator_v1.net"
NC_LEDGER = V1 / "netlist" / "nc_pins.json"
OUT = HERE / "interrogator_v1.kicad_pcb"

GAP = 0.8

# ---------------------------------------------------------------------------
# components.json part -> refdes table (all 41 majors). Lists = co-placed.
PLACEMENT_TABLE = {
    "MLX90642 thermal 32x24": ["U_MLX42"],
    "VL53L8CH ToF 8x8 raw":   ["U_VL53"],
    "TCS3448 14ch VIS":       ["U_TCS"],
    "AS7331 UV A/B/C":        ["U_AS7331"],
    "AS7421 64ch NIR +":      ["U_AS7421"],
    "MLX90632 spot FIR +":    ["U_MLX32"],
    "VD66GY camera (DNP)":    ["J_CAM"],
    "TXU0304 SPI shifter +":  ["U_LS_VL53"],
    "PCA9306 I2C xlate +":    ["U_XLAT_TCS"],
    "BME688 gas/T/RH/P":      ["U_BME"],
    "SGP41 VOC/NOx":          ["U_SGP"],
    "ENS161 4-el MOX +":      ["U_ENS"],
    "SCD41 true CO2 +":       ["U_SCD"],
    "SHT41 ref T/RH +":       ["U_SHT"],
    "BMV080 PM2.5":           ["U_BMV"],
    "MAX30102 PPG":           ["U_MAX"],
    "AS7058 PPG/ECG/BioZ":    ["U_AS7058"],
    "A121 60GHz radar":       ["U_A121"],
    "MMC5983MA nT mag +":     ["U_MMC"],
    "TMAG5273 mT hall":       ["U_TMAG"],
    "STM32N657 VFBGA142":     ["U_N657"],
    "48MHz HSE crystal +":    ["X_HSE"],
    "Octal NOR flash":        ["U_NOR"],
    "IQS7222A touch":         ["U_TOUCH"],
    "DRV2605L haptic":        ["U_HAP"],
    "MIA-M10Q GNSS RAWX":     ["U_GNSS"],
    "BL54L15 BLE sentinel":   ["U_BL54"],
    "ESP32-C6-MINI WiFi":     ["U_C6"],
    "BNO086 IMU raw+fused":   ["U_BNO"],
    "ADS131M04 24b 4ch":      ["U_ADS"],
    "PIN radiation det +":    ["D_PIN", "SH_RAD"],          # concentric block
    "MEMS mic +":             ["MK1"],
    "SGX-4CO electrochem +":  ["U_CO"],
    "CYPD3177 USB-C PD":      ["U_PD"],
    "BQ25620 charger 3.5A":   ["U_CHG"],
    "BQ27427 gauge":          ["U_GAUGE"],
    "TPS62840 sentinel buck": ["U_AON"],
    "TPS62823 core buck":     ["U_CORE"],
    "TLV62568 1V8 buck":      ["U_1V8"],
    "BQ29700+FET protect":    ["U_PROT", "Q_PROT"],         # side by side
    "Load switches x10":      ["U_SW_OPTICAL", "U_SW_AIR", "U_SW_CONTACT",
                               "U_SW_RADAR", "U_SW_GNSS", "U_SW_WIFI",
                               "U_SW_ACC", "U_SW1V8_OPTICAL",
                               "U_SW1V8_RADAR", "U_SW1V8_AIR"],  # row of 10
    # H3.2 MECH stage (design_v1.py place_mech): connectors/electrodes/
    # debug/antenna now have packed slots too.
    "USB-C receptacle":       ["J_USB"],
    "GNSS chip antenna":      ["AE_GNSS"],
    "Pogo landing field +":   ["J_POGO"],
    "Touch flex ZIF +":       ["J_TOUCH"],
    "RF survey U.FL +":       ["J_RF"],
    "ECG land L +":           ["E_ECG_L"],
    "ECG land R +":           ["E_ECG_R"],
    "ECG land REF +":         ["E_ECG_REF"],
    "Piezo disc pads":        ["PZ1"],
    "Battery connector":      ["J_BATT"],
    "SWD N6 tag-connect":     ["J_SWD_N6"],
    "SWD BL54 tag-connect":   ["J_SWD_BL"],
    "LRA pads":               ["J_LRA"],
    "Fan connector":          ["J_FAN"],
}
# note: U_SYS3V3 (the H2 stage-1 second TPS62823) is deliberately NOT a
# floorplan major — it is anchor-placed in the power zone like the other
# regulator passives (its 1.6x2.1 SOT-583 is passive-scale).

# per-ref extra rotation (degrees CCW, applied before bottom-side flip).
ROTATE = {
    "U_AS7331": 90,   # real OLGA16 is 2.6 x 3.65 portrait; packed slot is 3.65 x 2.6
}


def parse_netlist(text):
    comps = {}
    for m in re.finditer(r'\(comp\s*\(ref "([^"]+)"\).*?\(footprint "([^"]+)"\)',
                         text, re.S):
        comps[m.group(1)] = m.group(2)
    nets_txt = text[text.index("(nets"):]
    nets = {}
    for m in re.finditer(
            r'\(net\s*\(code \d+\)\s*\(name "([^"]+)"\)(.*?)(?=\(net\s*\(code|\Z)',
            nets_txt, re.S):
        nets[m.group(1)] = re.findall(r'\(ref "([^"]+)"\)\s*\(pin "([^"]+)"\)',
                                      m.group(2))
    return comps, nets


def load_fp(fpid):
    lib, name = fpid.split(":", 1)
    for d in (LIB / f"{lib}.pretty", LIB / "generated", OFFICIAL / f"{lib}.pretty"):
        if (d / f"{name}.kicad_mod").exists():
            fp = pcbnew.FootprintLoad(str(d), name)
            if fp:
                return fp
    return None


def mm(v):
    return pcbnew.FromMM(float(v))


def fp_extent_mm(fp):
    """Courtyard extent if drawn, else bbox (no text) — placement footprint."""
    xs, ys = [], []
    for g in fp.GraphicalItems():
        if g.GetLayer() in (pcbnew.F_CrtYd, pcbnew.B_CrtYd):
            bb = g.GetBoundingBox()
            xs += [bb.GetLeft(), bb.GetRight()]
            ys += [bb.GetTop(), bb.GetBottom()]
    if xs and (max(xs) - min(xs)) > 0:
        return (pcbnew.ToMM(max(xs) - min(xs)), pcbnew.ToMM(max(ys) - min(ys)))
    bb = fp.GetBoundingBox(False, False)
    return pcbnew.ToMM(bb.GetWidth()), pcbnew.ToMM(bb.GetHeight())


def edge_y(bean, x0, x1, top=True, n=21):
    """Bean boundary y over the x span (max y if top edge, min y if bottom)."""
    ys = []
    for x in np.linspace(x0, x1, n):
        line = LineString([(x, -5), (x, 60)])
        inter = line.intersection(bean)
        if inter.is_empty:
            continue
        lo, hi = inter.bounds[1], inter.bounds[3]
        ys.append(hi if top else lo)
    return (min(ys) if top else max(ys))


def main():
    outline = json.loads((V1 / "outline.json").read_text())
    bean = Polygon(outline["points_mm"])
    H = outline["width_mm"]            # board y-extent (KiCad y-flip reference)
    BW = outline["length_mm"]          # board x-extent
    comps_pos = {c["name"]: c for c in json.loads((V1 / "components.json").read_text())}

    comps, nets = parse_netlist(NETLIST.read_text())
    nc = json.loads(NC_LEDGER.read_text())["nc"]
    ncset = {(r, p) for r, ps in nc.items() for p in ps}
    print(f"netlist: {len(comps)} comps, {len(nets)} nets, "
          f"{sum(len(v) for v in nets.values())} pins; "
          f"nc ledger: {len(ncset)} declared pins")

    board = pcbnew.NewBoard(str(OUT))

    # ---- board setup: 6-layer stack + baseline rules ----------------------
    bds = board.GetDesignSettings()
    bds.SetCopperLayerCount(6)          # JLCPCB 6L through-via + POFV (H3 ratified)
    dnc = bds.m_NetSettings.m_DefaultNetClass
    dnc.SetClearance(mm(0.1))           # default 0.1 / 0.1 (JLC 6L capability)
    dnc.SetTrackWidth(mm(0.1))
    dnc.SetViaDiameter(mm(0.45))
    dnc.SetViaDrill(mm(0.2))
    bds.m_CopperEdgeClearance = mm(0.2)
    bds.m_MinClearance = mm(0.09)       # floor: BGA fanout class (kicad_dru)
    bds.m_TrackMinWidth = mm(0.09)

    netinfo = {}
    for name in sorted(nets):
        ni = pcbnew.NETINFO_ITEM(board, name)
        board.Add(ni)
        netinfo[name] = ni
    pad_net = {}
    for name, nodes in nets.items():
        for ref, pin in nodes:
            pad_net[(ref, pin)] = name

    # ---- fixed placements from components.json ----------------------------
    fixed = {}     # ref -> (cx_board, cy_board, side, rot)  [board frame, y up]
    for part, refs in PLACEMENT_TABLE.items():
        c = comps_pos[part]
        x, y, w, h = c["x_mm"], c["y_mm"], c["w_mm"], c["h_mm"]
        side = c["side"]
        rot = 90 if "rot=90" in c.get("note", "") else 0   # mech auto-slots
        if len(refs) == 1 or part == "PIN radiation det +":
            for ref in refs:                     # concentric (D_PIN + SH_RAD)
                fixed[ref] = (x + w / 2, y + h / 2, side, rot)
        elif part == "BQ29700+FET protect":
            fixed[refs[0]] = (x + w * 0.28, y + h / 2, side, 0)
            fixed[refs[1]] = (x + w * 0.75, y + h / 2, side, 0)
        else:                                    # row distribution (switches)
            pitch = w / len(refs)
            for i, ref in enumerate(refs):
                fixed[ref] = (x + pitch * (i + 0.5), y + h / 2, side, 0)
    bl_cx, bl_cy, _bs, _br = fixed["U_BL54"]     # already rim-flush (design_v1)

    # ---- occupancy grid ----------------------------------------------------
    RES = 0.2    # H3.2: 0.25 quantization cost ~0.4mm2 per passive at this density
    nx, ny = int(BW / RES) + 2, int(H / RES) + 2   # derived from the outline bbox
    occ = {"top": np.zeros((nx, ny), bool), "bot": np.zeros((nx, ny), bool)}
    shrunk = bean.buffer(-0.55)          # copper-edge clearance 0.2 + pad margin
    inside = np.zeros((nx, ny), bool)
    for i in range(nx):
        for j in range(ny):
            inside[i, j] = shrunk.contains(Point(i * RES, j * RES))

    def cells(cx, cy, w, h):
        i0 = max(0, int((cx - w / 2 - 0.02) / RES))
        i1 = min(nx, int((cx + w / 2 + 0.02) / RES) + 1)
        j0 = max(0, int((cy - h / 2 - 0.02) / RES))
        j1 = min(ny, int((cy + h / 2 + 0.02) / RES) + 1)
        return i0, i1, j0, j1

    def mark(side, cx, cy, w, h):
        i0, i1, j0, j1 = cells(cx, cy, w, h)
        occ[side][i0:i1, j0:j1] = True

    # H3.2 low-profile / shielded region masks:
    #  * SGX can (bot): the cell plugs onto >=1.5mm receptacles — the O20.9
    #    region under the can accepts 0402/0603-class dust (maxdim <= 2.0mm).
    #  * shield can interior (top): only the radiation front-end parts may
    #    live inside (light-tight cavity; foreign nets stay out).
    canmask = np.zeros((nx, ny), bool)      # bot only
    shieldmask = np.zeros((nx, ny), bool)   # top only

    def free(side, cx, cy, w, h, dust=False, rad=False):
        i0, i1 = int((cx - w / 2) / RES), int((cx + w / 2) / RES) + 1
        j0, j1 = int((cy - h / 2) / RES), int((cy + h / 2) / RES) + 1
        if i0 < 0 or j0 < 0 or i1 > nx or j1 > ny:
            return False
        if not inside[i0:i1, j0:j1].all():
            return False
        blocked = occ[side][i0:i1, j0:j1]
        if side == "bot" and not dust:
            blocked = blocked | canmask[i0:i1, j0:j1]
        if side == "top" and not rad:
            blocked = blocked | shieldmask[i0:i1, j0:j1]
        return not blocked.any()

    # ---- instantiate footprints -------------------------------------------
    footprints, missing = {}, []
    for ref, fpid in sorted(comps.items()):
        fp = load_fp(fpid)
        if fp is None:
            missing.append((ref, fpid))
            continue
        fp.SetReference(ref)
        footprints[ref] = fp
        board.Add(fp)
    if missing:
        print("MISSING FOOTPRINTS:")
        for r, f in missing:
            print("  ", r, f)
        sys.exit(1)

    def court_bbox(fp):
        """Courtyard bbox in absolute KiCad coords (falls back to fp bbox)."""
        xs, ys = [], []
        for g in fp.GraphicalItems():
            if g.GetLayer() in (pcbnew.F_CrtYd, pcbnew.B_CrtYd):
                bb = g.GetBoundingBox()
                xs += [bb.GetLeft(), bb.GetRight()]
                ys += [bb.GetTop(), bb.GetBottom()]
        if not xs or max(xs) == min(xs):
            bb = fp.GetBoundingBox(False, False)
            return bb.GetLeft(), bb.GetTop(), bb.GetRight(), bb.GetBottom()
        return min(xs), min(ys), max(xs), max(ys)

    def place(ref, cx, cy, side, rot=0, center=True):
        """cx/cy in board frame (y up); handles KiCad y-flip + side flip.
        The footprint is shifted so its COURTYARD CENTER lands on (cx,cy) —
        connector origins (FH12/USB/JST) are not their courtyard centers,
        which let dust into real courtyard area at H2. Returns actual (w,h).
        center=False keeps the footprint ORIGIN on the slot center (U_CO:
        the ring courtyard is asymmetric but the CAN center is the origin)."""
        fp = footprints[ref]
        fp.SetOrientationDegrees(0)
        if fp.IsFlipped():
            fp.Flip(fp.GetPosition(), False)
        fp.SetPosition(pcbnew.VECTOR2I(mm(cx), mm(H - cy)))
        if rot:
            fp.SetOrientationDegrees(rot)
        if side == "bot":
            fp.Flip(fp.GetPosition(), False)
        x0, y0, x1, y1 = court_bbox(fp)
        if center:
            dx = mm(cx) - (x0 + x1) // 2
            dy = mm(H - cy) - (y0 + y1) // 2
            fp.Move(pcbnew.VECTOR2I(int(dx), int(dy)))
        return pcbnew.ToMM(x1 - x0), pcbnew.ToMM(y1 - y0)

    def mark_holes(ref):
        """TH/NPTH pads pierce the board: block BOTH side grids (+0.3)."""
        fp = footprints[ref]
        for pad in fp.Pads():
            if pad.GetDrillSizeX() > 0:
                pos = pad.GetPosition()
                px, py = pcbnew.ToMM(pos.x), H - pcbnew.ToMM(pos.y)
                r = max(pcbnew.ToMM(pad.GetSizeX()),
                        pcbnew.ToMM(pad.GetSizeY())) + 0.6
                for sd in ("top", "bot"):
                    mark(sd, px, py, r, r)

    # BL54 orientation: pick the rotation that puts the antenna keep-out
    # (the Dwgs.User dashed rect at the pin-1 end) toward the +y rim
    # (minimum KiCad y), after the bottom-side flip is applied.
    def bl54_rotation():
        fp = footprints["U_BL54"]      # board-owned (orphan Flip segfaults)
        fp.SetPosition(pcbnew.VECTOR2I(mm(bl_cx), mm(H - bl_cy)))
        best, best_y = 0, 1e9
        for rot in (0, 90, 180, 270):
            if fp.IsFlipped():
                fp.Flip(fp.GetPosition(), False)
            fp.SetOrientationDegrees(rot)
            fp.Flip(fp.GetPosition(), False)   # module lives on the bottom
            ys = []
            for gitem in fp.GraphicalItems():
                if gitem.GetLayer() == pcbnew.Dwgs_User:
                    bb = gitem.GetBoundingBox()
                    ys += [bb.GetTop(), bb.GetBottom()]
            yc = pcbnew.ToMM(sum(ys) / len(ys))
            if yc < best_y:
                best, best_y = rot, yc
        if fp.IsFlipped():                     # restore; place() re-applies
            fp.Flip(fp.GetPosition(), False)
        fp.SetOrientationDegrees(0)
        return best

    slot_wh = {}    # ref -> packed slot (w, h) for aspect checks
    for part, refs in PLACEMENT_TABLE.items():
        c = comps_pos[part]
        if len(refs) == 1:
            slot_wh[refs[0]] = (c["w_mm"], c["h_mm"])

    placed_n = 0
    for ref, (cx, cy, side, mrot) in fixed.items():
        rot = ROTATE.get(ref, mrot)
        if ref == "U_BL54":
            rot = bl54_rotation()
        w, h = place(ref, cx, cy, side, rot, center=(ref != "U_CO"))
        # auto aspect-match: if the footprint's native orientation doesn't
        # match the packed slot's aspect (e.g. U_MAX OLGA-14 is 3.3x5.6 but
        # the slot is 5.6x3.3), rotate 90 (fixes H2's pad-overlap class).
        if ref in slot_wh and abs(w - h) > 0.3:
            sw, sh = slot_wh[ref]
            if abs(sw - sh) > 0.3 and ((sw > sh) != (w > h)):
                rot += 90
                w, h = place(ref, cx, cy, side, rot)
        if ref == "U_CO":
            # receptacle sites block everyone (marked from the REAL flipped
            # pad positions — the courtyard rings are r2.1 around each pad);
            # the rest of the can region is dust-legal
            for pad in footprints[ref].Pads():
                pos = pad.GetPosition()
                # receptacle courtyard rings are r2.1 (O4.2) — 4.8 marks
                # keep 0.3 margin (was 5.4; H3.3b capacity relief)
                mark(side, pcbnew.ToMM(pos.x), H - pcbnew.ToMM(pos.y), 4.8, 4.8)
            i0, i1, j0, j1 = cells(cx, cy, 20.9, 20.9)
            canmask[i0:i1, j0:j1] = True
        elif ref == "SH_RAD":
            for sx, sy in ((-1, -1), (-1, 1), (1, 1), (1, -1)):
                mark(side, cx + sx * 4.6, cy + sy * 4.6, 2.2, 2.2)
            i0, i1, j0, j1 = cells(cx, cy, 8.6, 8.6)   # interior, tabs excluded
            shieldmask[i0:i1, j0:j1] = True
        else:
            mark(side, cx, cy, max(w, 0.8), max(h, 0.8))
            # H3.3a: via-in-pad POFV fanout fields pierce the board — keep
            # the OPPOSITE face clear of dust over the BALL FIELD (+0.35
            # via/clearance halo; the courtyard ring outside the field is
            # legal dust space). D_GLOW/Q_WHITE used to land over the N657
            # field; J_SWD_BL under the A121.
            if ref in ("U_N657", "U_A121"):
                bxs = [pcbnew.ToMM(pd.GetPosition().x)
                       for pd in footprints[ref].Pads()]
                bys = [pcbnew.ToMM(pd.GetPosition().y)
                       for pd in footprints[ref].Pads()]
                fw = max(bxs) - min(bxs) + 0.7
                fh = max(bys) - min(bys) + 0.7
                mark("top" if side == "bot" else "bot",
                     (min(bxs) + max(bxs)) / 2,
                     H - (min(bys) + max(bys)) / 2, fw, fh)
        mark_holes(ref)
        placed_n += 1
    # sanity: the BL54 keep-out must point at the rim
    print(f"BL54 rotation: {footprints['U_BL54'].GetOrientationDegrees():.0f} deg")

    # ---- anchor-driven spiral placement for everything else ---------------
    # anchor(ref) = weighted centroid of already-placed parts sharing a net
    # (weight 1/(nodes-1): GND/rails contribute ~nothing, local nets dominate).
    weights = {}
    for name, nodes in nets.items():
        if len(nodes) < 2:
            continue
        wgt = 1.0 / (len(nodes) - 1)
        refs_in = {r for r, _ in nodes}
        for r in refs_in:
            for r2 in refs_in:
                if r != r2:
                    weights.setdefault(r, {})
                    weights[r][r2] = weights[r].get(r2, 0.0) + wgt

    placed_pos = {r: (c[0], c[1], c[2]) for r, c in fixed.items()}
    # radiation front-end refs — the only parts allowed inside the shield can
    RADNETS = {"RAD_IN", "RAD_VREF", "RAD_ANALOG", "PIN_BIAS", "RAD_VTH",
               "GEIGER_PULSE", "SHIELD_RAD"}
    radset = {r for n in RADNETS if n in nets for r, _pin in nets[n]}
    offsets = sorted(((dx * RES, dy * RES)
                      for dx in range(-(nx - 1), nx)
                      for dy in range(-(ny - 1), ny)),
                     key=lambda o: o[0] * o[0] + o[1] * o[1])

    grid_parts = [r for r in footprints if r not in fixed]
    # H3.3b fix: crystal load caps / LDO CAP caps MUST land beside their
    # ICs — place them before the ordinary dust exhausts that space
    # (C68 used to end up 20mm from the 48MHz crystal).
    PRIORITY_NETS = {"N6_OSC_IN", "N6_OSC_OUT", "A121_XIN", "A121_XOUT",
                     "ADS_CAP", "BNO_CAP", "N6_V08CAP"}
    prio = {r for n in PRIORITY_NETS if n in nets for r, _p in nets[n]
            if r in footprints and r not in fixed}
    grid_parts.sort(key=lambda r: (0 if r in prio else 1,
                                   -fp_extent_mm(footprints[r])[0]
                                   * fp_extent_mm(footprints[r])[1]))
    unplaced = []
    for ref in grid_parts:
        w0, h0 = fp_extent_mm(footprints[ref])
        w0, h0 = max(w0, 0.8), max(h0, 0.8)
        # anchor + preferred side from placed neighbours
        ax = ay = tot = 0.0
        side_w = {"top": 0.0, "bot": 0.0}
        for other, wgt in weights.get(ref, {}).items():
            if other in placed_pos:
                px, py, ps = placed_pos[other]
                ax += px * wgt
                ay += py * wgt
                tot += wgt
                side_w[ps] += wgt
        if tot > 0:
            ax, ay = ax / tot, ay / tot
            pref = "bot" if side_w["bot"] >= side_w["top"] else "top"
        else:
            ax, ay, pref = 34.0, 20.0, "bot"
        other_side = "top" if pref == "bot" else "bot"
        # SGX under-can eligibility: chip R/C/TP up to 0805 class (part
        # height <=1.25mm vs >=1.5mm receptacle standoff; the H4 receptacle-
        # height check covers this together with the N657 rim note)
        dust = (max(w0, h0) <= 3.0
                and (ref[0] in "CR" or ref.startswith("TP")))
        rad = ref in radset                  # shield-interior eligibility
        done = False
        for side in (pref, other_side):
            for dx, dy in offsets:
                cx, cy = ax + dx, ay + dy
                for w, h, rot in ((w0, h0, 0), (h0, w0, 90)):
                    if abs(w - h) < 0.01 and rot:
                        continue
                    if free(side, cx, cy, w, h, dust=dust, rad=rad):
                        place(ref, cx, cy, side, rot)
                        mark(side, cx, cy, w, h)
                        mark_holes(ref)
                        placed_pos[ref] = (cx, cy, side)
                        done = True
                        break
                if done:
                    break
            if done:
                break
        if not done:
            # second chance: 0.1mm offset grid (the 0.2 spiral cannot align
            # into the last slivers on a board this full)
            for side in (pref, other_side):
                for dx, dy in offsets:
                    for fx, fy in ((0.1, 0.0), (0.0, 0.1), (0.1, 0.1)):
                        cx, cy = ax + dx + fx, ay + dy + fy
                        for w, h, rot in ((w0, h0, 0), (h0, w0, 90)):
                            if abs(w - h) < 0.01 and rot:
                                continue
                            if free(side, cx, cy, w, h, dust=dust, rad=rad):
                                place(ref, cx, cy, side, rot)
                                mark(side, cx, cy, w, h)
                                mark_holes(ref)
                                placed_pos[ref] = (cx, cy, side)
                                done = True
                                break
                        if done:
                            break
                    if done:
                        break
                if done:
                    break
        if not done:
            unplaced.append(ref)
    if unplaced:
        print(f"PLACEMENT FAILURE — no collision-free slot for: {unplaced}")
        print("fix boards/v1/design_v1.py zones and repack (no fallback exists)")
        dustfree = (inside & ~occ["bot"]).sum() * RES * RES
        print(f"debug: bot dust-free {dustfree:.0f}mm2; canmask cells "
              f"{canmask.sum()}, occ-under-can "
              f"{(occ['bot'] & canmask).sum()}/{canmask.sum()}")
        np.savez("/tmp/occ_debug.npz", top=occ["top"], bot=occ["bot"],
                 inside=inside, canmask=canmask)
        sys.exit(1)

    # ---- pad -> net binding (hard-gated) -----------------------------------
    bound = mech = declared_nc = 0
    bound_keys = set()
    undeclared = []
    for ref, fp in footprints.items():
        for pad in fp.Pads():
            num = pad.GetNumber()
            if num == "":
                mech += 1               # NPTH / paste aperture / mech pad
                continue
            key = (ref, num)
            if key in pad_net:
                pad.SetNet(netinfo[pad_net[key]])
                bound += 1
                bound_keys.add(key)
            elif key in ncset:
                declared_nc += 1        # justified no-connect (nc_pins.json)
            else:
                undeclared.append(key)
    lost = [k for k in pad_net if k not in bound_keys]
    if undeclared or lost:
        print(f"PAD-BINDING FAILURE — undeclared unbound pads: {undeclared[:20]}")
        print(f"netlist pins with no pad: {lost[:20]}")
        sys.exit(1)

    # ---- Edge.Cuts bean polygon --------------------------------------------
    pts = outline["points_mm"]
    for k in range(len(pts)):
        x1, y1 = pts[k]
        x2, y2 = pts[(k + 1) % len(pts)]
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetStart(pcbnew.VECTOR2I(mm(x1), mm(H - y1)))
        seg.SetEnd(pcbnew.VECTOR2I(mm(x2), mm(H - y2)))
        seg.SetLayer(pcbnew.Edge_Cuts)
        seg.SetWidth(mm(0.1))
        board.Add(seg)

    board.Save(str(OUT))

    # ---- seed H3.3 net classes into the project file ----------------------
    # KiCad 7 stores netclass definitions + pattern assignments in the
    # .kicad_pro (the board file carries none) — the project file is now
    # COMMITTED (checked: CI's eda glob `boards/*/*.kicad_pro` does not reach
    # boards/v1/board/). Values for the diff classes are PLACEHOLDERS until
    # the H3.3 impedance calc against the ratified JLC 6L stackup.
    def klass(name, clearance, track, extra=None):
        d = {"bus_width": 12, "clearance": clearance, "diff_pair_gap": 0.25,
             "diff_pair_via_gap": 0.25, "diff_pair_width": 0.2,
             "line_style": 0, "microvia_diameter": 0.3, "microvia_drill": 0.1,
             "name": name, "pcb_color": "rgba(0, 0, 0, 0.000)",
             "schematic_color": "rgba(0, 0, 0, 0.000)", "track_width": track,
             "via_diameter": 0.4, "via_drill": 0.2, "wire_width": 6}
        if extra:
            d.update(extra)
        return d

    pro_path = OUT.with_suffix(".kicad_pro")
    pro = json.loads(pro_path.read_text())
    pro["net_settings"] = {
        "classes": [
            klass("Default", 0.1, 0.09),
            klass("PWR", 0.1, 0.15),
            # 90R diff placeholder (USB HS) — tune vs JLC 6L stackup at H3.3
            klass("USB_HS", 0.1, 0.13,
                  {"diff_pair_width": 0.13, "diff_pair_gap": 0.15}),
            # 100R diff placeholder (MIPI CSI-2 x2 lanes + clock)
            klass("CSI", 0.1, 0.11,
                  {"diff_pair_width": 0.11, "diff_pair_gap": 0.15}),
            # 50R single-ended placeholder (GNSS RF feed, SMA survey input)
            klass("RF", 0.2, 0.3),
            # VFBGA142 quadrant fanout (also enforced area-wise by .kicad_dru)
            klass("BGA_FANOUT", 0.09, 0.09),
        ],
        "meta": {"version": 3},
        "net_colors": None,
        "netclass_assignments": None,
        "netclass_patterns": [
            {"netclass": "PWR", "pattern": p} for p in
            ("GND", "VSYS", "VBAT", "VBUS_C", "PACKP", "CELL_N", "PROT_MID",
             "VACC", "VDD_CORE_N6", "3V3_*", "1V8*")
        ] + [
            {"netclass": "USB_HS", "pattern": "USB_D*"},
            {"netclass": "CSI", "pattern": "CSI_*"},
            {"netclass": "RF", "pattern": "GNSS_RF"},
            {"netclass": "RF", "pattern": "RF_IN"},
        ],
    }
    # H3.3a: the global rules floor must admit the 0.2/0.4 POFV fanout via
    # (pcbnew's NewBoard defaults were 0.5/0.3 and clamp the netclasses);
    # hole-to-copper 0.2 = JLC 6L capability (dru relaxes to 0.15 inside
    # the via-in-pad courtyards only).
    rules = pro.setdefault("board", {}).setdefault("design_settings", {}).setdefault("rules", {})
    rules["min_via_diameter"] = 0.4
    rules["min_through_hole_diameter"] = 0.2
    rules["min_hole_clearance"] = 0.2
    pro_path.write_text(json.dumps(pro, indent=2))
    # .kicad_prl is per-user UI state — not committed
    prl = OUT.with_suffix(".kicad_prl")
    if prl.exists():
        prl.unlink()

    n_top = sum(1 for r, p in placed_pos.items() if p[2] == "top")
    print(f"placed: fixed-packed={placed_n} anchor-spiral={len(grid_parts)} "
          f"overlap-fallback=0 (hard-gated); top={n_top} bot={len(placed_pos) - n_top}")
    print(f"pads: bound={bound} declared-NC={declared_nc} mech/paste(unnumbered)={mech}")
    print(f"netlist pins covered: {len(bound_keys)}/{len(pad_net)}")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
